#!/usr/bin/env node
'use strict';

/**
 * Angular Service Scaffolder
 *
 * Generates service files (.ts, .spec.ts) from a name and optional method list.
 *
 * Usage:
 *   node scripts/scaffold-service.js <service-name> [options]
 *
 * Options:
 *   --methods "getAll,getById,create,delete"   CRUD methods to generate
 *   --path <dir>                               Target directory (default: src/app/services)
 *
 * Output (stdout): JSON  { files: [{ path, content }] }
 * Progress (stderr): human-readable status messages.
 * Exit: 0 on success, 1 on error.
 */

const path = require('path');

// ─── Argument parsing ───────────────────────────────────────
const args = process.argv.slice(2);
const log = (msg) => process.stderr.write(`[scaffold-service] ${msg}\n`);

function option(name, fallback) {
  const idx = args.indexOf(`--${name}`);
  return idx !== -1 && args[idx + 1] ? args[idx + 1] : fallback;
}

const serviceName = args.find((a) => !a.startsWith('--'));
if (!serviceName) {
  log('ERROR: Service name is required.\n  Usage: node scaffold-service.js <name> [--methods "m1,m2"] [--path <dir>]');
  process.exit(1);
}

const rawMethods = option('methods', 'getAll,getById,create,delete');
const methods = rawMethods.split(',').map((m) => m.trim()).filter(Boolean);
const targetDir = option('path', 'src/app/services');

log(`Scaffolding service: ${serviceName}`);
log(`  methods=${methods.join(',')}  target=${targetDir}`);

// ─── Helpers ─────────────────────────────────────────────────
function toClassName(name) {
  return name
    .split('-')
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join('');
}

const className = toClassName(serviceName);
const modelName = className;
const files = [];

// ─── Service TypeScript ──────────────────────────────────────
function buildServiceTs() {
  const lines = [
    `// ${serviceName}.service.ts — generated by scaffold-service`,
    `import { Injectable, inject } from '@angular/core';`,
    `import { HttpClient, HttpErrorResponse } from '@angular/common/http';`,
    `import { Observable, catchError, map, retry, throwError } from 'rxjs';`,
    '',
    `import { LoggingService } from '@core/services/logging.service';`,
    `import { ConfigService } from '@core/services/config.service';`,
    '',
    `/**`,
    ` * Manages ${serviceName} data operations.`,
    ` *`,
    ` * @remarks`,
    ` * All requests use the environment-aware base URL from {@link ConfigService}.`,
    ` * Failures are logged via {@link LoggingService} before propagating.`,
    ` */`,
    `@Injectable({ providedIn: 'root' })`,
    `export class ${className}Service {`,
    `  private readonly http = inject(HttpClient);`,
    `  private readonly logger = inject(LoggingService);`,
    `  private readonly config = inject(ConfigService);`,
    '',
    `  private get baseUrl(): string {`,
    `    return \`\${this.config.getApiBaseUrl()}/api/v1/${serviceName}s\`;`,
    `  }`,
    '',
  ];

  // Generate method bodies based on method names
  for (const method of methods) {
    if (method === 'getAll') {
      lines.push(
        `  /**`,
        `   * Retrieves all ${serviceName} records.`,
        `   */`,
        `  getAll(): Observable<${modelName}[]> {`,
        `    return this.http.get<${modelName}[]>(this.baseUrl).pipe(`,
        `      retry({ count: 1, delay: 1000 }),`,
        `      catchError((err: HttpErrorResponse) => this.handleError('getAll', err)),`,
        `    );`,
        `  }`,
        '',
      );
    } else if (method === 'getById') {
      lines.push(
        `  /**`,
        `   * Retrieves a single ${serviceName} by ID.`,
        `   * @param id - Unique identifier.`,
        `   */`,
        `  getById(id: string): Observable<${modelName}> {`,
        `    return this.http.get<${modelName}>(\`\${this.baseUrl}/\${id}\`).pipe(`,
        `      catchError((err: HttpErrorResponse) => this.handleError('getById', err)),`,
        `    );`,
        `  }`,
        '',
      );
    } else if (method === 'create') {
      lines.push(
        `  /**`,
        `   * Creates a new ${serviceName} record.`,
        `   * @param payload - The data to create.`,
        `   */`,
        `  create(payload: Partial<${modelName}>): Observable<${modelName}> {`,
        `    this.logger.info('${className}Service', \`Creating ${serviceName}\`);`,
        `    return this.http.post<${modelName}>(this.baseUrl, payload).pipe(`,
        `      catchError((err: HttpErrorResponse) => this.handleError('create', err)),`,
        `    );`,
        `  }`,
        '',
      );
    } else if (method === 'delete') {
      lines.push(
        `  /**`,
        `   * Deletes a ${serviceName} record by ID.`,
        `   * @param id - Unique identifier.`,
        `   */`,
        `  delete(id: string): Observable<void> {`,
        `    this.logger.info('${className}Service', \`Deleting ${serviceName}: \${id}\`);`,
        `    return this.http.delete<void>(\`\${this.baseUrl}/\${id}\`).pipe(`,
        `      catchError((err: HttpErrorResponse) => this.handleError('delete', err)),`,
        `    );`,
        `  }`,
        '',
      );
    } else {
      // Generic custom method
      lines.push(
        `  /**`,
        `   * Executes the ${method} operation.`,
        `   */`,
        `  ${method}(params?: Record<string, unknown>): Observable<unknown> {`,
        `    this.logger.info('${className}Service', \`Executing ${method}\`);`,
        `    return this.http.post(\`\${this.baseUrl}/${method}\`, params ?? {}).pipe(`,
        `      catchError((err: HttpErrorResponse) => this.handleError('${method}', err)),`,
        `    );`,
        `  }`,
        '',
      );
    }
  }

  // Error handler
  lines.push(
    `  private handleError(method: string, error: HttpErrorResponse): Observable<never> {`,
    `    this.logger.error('${className}Service', \`\${method} failed: \${error.status} \${error.message}\`);`,
    `    return throwError(() => error);`,
    `  }`,
    `}`,
    '',
  );

  files.push({ path: path.join(targetDir, `${serviceName}.service.ts`), content: lines.join('\n') });
}

// ─── Spec file ───────────────────────────────────────────────
function buildServiceSpec() {
  const lines = [
    `// ${serviceName}.service.spec.ts — generated by scaffold-service`,
    `import { TestBed } from '@angular/core/testing';`,
    `import { HttpClientTestingModule, HttpTestingController } from '@angular/common/http/testing';`,
    '',
    `import { ${className}Service } from './${serviceName}.service';`,
    `import { LoggingService } from '@core/services/logging.service';`,
    `import { ConfigService } from '@core/services/config.service';`,
    '',
    `describe('${className}Service', () => {`,
    `  let service: ${className}Service;`,
    `  let httpMock: HttpTestingController;`,
    `  let loggerSpy: jasmine.SpyObj<LoggingService>;`,
    `  let configSpy: jasmine.SpyObj<ConfigService>;`,
    '',
    `  const BASE_URL = 'https://api.test.example.com';`,
    '',
    `  beforeEach(() => {`,
    `    loggerSpy = jasmine.createSpyObj('LoggingService', ['info', 'error', 'warn']);`,
    `    configSpy = jasmine.createSpyObj('ConfigService', ['getApiBaseUrl']);`,
    `    configSpy.getApiBaseUrl.and.returnValue(BASE_URL);`,
    '',
    `    TestBed.configureTestingModule({`,
    `      imports: [HttpClientTestingModule],`,
    `      providers: [`,
    `        ${className}Service,`,
    `        { provide: LoggingService, useValue: loggerSpy },`,
    `        { provide: ConfigService, useValue: configSpy },`,
    `      ],`,
    `    });`,
    '',
    `    service = TestBed.inject(${className}Service);`,
    `    httpMock = TestBed.inject(HttpTestingController);`,
    `  });`,
    '',
    `  afterEach(() => httpMock.verify());`,
    '',
    `  it('should be created', () => {`,
    `    expect(service).toBeTruthy();`,
    `  });`,
    '',
  ];

  // Generate test for each method
  if (methods.includes('getAll')) {
    lines.push(
      `  describe('getAll', () => {`,
      `    it('should GET all records', () => {`,
      `      const mockData = [{ id: '1' }, { id: '2' }];`,
      `      service.getAll().subscribe((result) => {`,
      `        expect(result.length).toBe(2);`,
      `      });`,
      `      const req = httpMock.expectOne(\`\${BASE_URL}/api/v1/${serviceName}s\`);`,
      `      expect(req.request.method).toBe('GET');`,
      `      req.flush(mockData);`,
      `    });`,
      `  });`,
      '',
    );
  }

  if (methods.includes('getById')) {
    lines.push(
      `  describe('getById', () => {`,
      `    it('should GET a single record by id', () => {`,
      `      service.getById('42').subscribe((result) => {`,
      `        expect(result.id).toBe('42');`,
      `      });`,
      `      const req = httpMock.expectOne(\`\${BASE_URL}/api/v1/${serviceName}s/42\`);`,
      `      expect(req.request.method).toBe('GET');`,
      `      req.flush({ id: '42' });`,
      `    });`,
      `  });`,
      '',
    );
  }

  if (methods.includes('create')) {
    lines.push(
      `  describe('create', () => {`,
      `    it('should POST and log the creation', () => {`,
      `      const payload = { name: 'test' };`,
      `      service.create(payload).subscribe();`,
      `      const req = httpMock.expectOne(\`\${BASE_URL}/api/v1/${serviceName}s\`);`,
      `      expect(req.request.method).toBe('POST');`,
      `      expect(req.request.body).toEqual(payload);`,
      `      req.flush({ id: '1', ...payload });`,
      `      expect(loggerSpy.info).toHaveBeenCalled();`,
      `    });`,
      `  });`,
      '',
    );
  }

  if (methods.includes('delete')) {
    lines.push(
      `  describe('delete', () => {`,
      `    it('should DELETE and log the removal', () => {`,
      `      service.delete('42').subscribe();`,
      `      const req = httpMock.expectOne(\`\${BASE_URL}/api/v1/${serviceName}s/42\`);`,
      `      expect(req.request.method).toBe('DELETE');`,
      `      req.flush(null);`,
      `      expect(loggerSpy.info).toHaveBeenCalled();`,
      `    });`,
      `  });`,
      '',
    );
  }

  lines.push(`});`, '');

  files.push({ path: path.join(targetDir, `${serviceName}.service.spec.ts`), content: lines.join('\n') });
}

// ─── Main ────────────────────────────────────────────────────
buildServiceTs();
buildServiceSpec();

log(`Generated ${files.length} file(s)`);
process.stdout.write(JSON.stringify({ files }, null, 2) + '\n');
