#!/usr/bin/env node
'use strict';

/**
 * Angular Route Scaffolder
 *
 * Generates route-related files (routes config, guard, resolver) from a
 * route name and optional flags.
 *
 * Usage:
 *   node scripts/scaffold-route.js <route-name> [options]
 *
 * Options:
 *   --guards          Include a functional route guard
 *   --resolver        Include a data resolver
 *   --lazy            Generate lazy-loaded route config (default: true)
 *   --path <dir>      Target directory (default: src/app/routes/<route-name>)
 *
 * Output (stdout): JSON  { files: [{ path, content }] }
 * Progress (stderr): human-readable status messages.
 * Exit: 0 on success, 1 on error.
 */

const path = require('path');

// ─── Argument parsing ───────────────────────────────────────
const args = process.argv.slice(2);
const log = (msg) => process.stderr.write(`[scaffold-route] ${msg}\n`);

function flag(name) {
  return args.includes(`--${name}`);
}

function option(name, fallback) {
  const idx = args.indexOf(`--${name}`);
  return idx !== -1 && args[idx + 1] ? args[idx + 1] : fallback;
}

const routeName = args.find((a) => !a.startsWith('--'));
if (!routeName) {
  log('ERROR: Route name is required.\n  Usage: node scaffold-route.js <route-name> [--guards] [--resolver] [--lazy] [--path <dir>]');
  process.exit(1);
}

const includeGuards = flag('guards');
const includeResolver = flag('resolver');
const lazy = !flag('no-lazy'); // lazy by default
const targetDir = option('path', `src/app/routes/${routeName}`);

log(`Scaffolding route: ${routeName}`);
log(`  guards=${includeGuards}  resolver=${includeResolver}  lazy=${lazy}`);
log(`  target=${targetDir}`);

// ─── Helpers ─────────────────────────────────────────────────
function toClassName(name) {
  return name
    .split('-')
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join('');
}

function toCamelCase(name) {
  const cls = toClassName(name);
  return cls.charAt(0).toLowerCase() + cls.slice(1);
}

const className = toClassName(routeName);
const camel = toCamelCase(routeName);
const files = [];

// ─── Route config ────────────────────────────────────────────
function buildRoutesFile() {
  const imports = [`import { Routes } from '@angular/router';`];
  const guardRef = includeGuards ? `${camel}Guard` : null;
  const resolverRef = includeResolver ? `${camel}DetailResolver` : null;

  if (guardRef) {
    imports.push(`import { ${guardRef} } from './${routeName}-auth.guard';`);
  }
  if (resolverRef) {
    imports.push(`import { ${resolverRef} } from './${routeName}-detail.resolver';`);
  }

  const routeObj = [];
  routeObj.push(`    path: '${routeName}'`);

  if (lazy) {
    routeObj.push(`    loadComponent: () => import('./${routeName}.component').then(m => m.${className}Component)`);
  } else {
    imports.push(`import { ${className}Component } from './${routeName}.component';`);
    routeObj.push(`    component: ${className}Component`);
  }

  if (guardRef) {
    routeObj.push(`    canActivate: [${guardRef}]`);
  }

  if (resolverRef) {
    routeObj.push(`    resolve: { detail: ${resolverRef} }`);
  }

  routeObj.push(`    title: '${className}'`);

  const content = [
    `// ${routeName}.routes.ts — generated by scaffold-route`,
    ...imports,
    '',
    'export const routes: Routes = [',
    '  {',
    routeObj.map((l) => `  ${l},`).join('\n'),
    '  },',
    '];',
    '',
  ].join('\n');

  files.push({ path: path.join(targetDir, `${routeName}.routes.ts`), content });
}

// ─── Guard ───────────────────────────────────────────────────
function buildGuardFile() {
  const content = [
    `// ${routeName}-auth.guard.ts — generated by scaffold-route`,
    `import { inject } from '@angular/core';`,
    `import { CanActivateFn, Router } from '@angular/router';`,
    `import { AuthService } from '@core/services/auth.service';`,
    '',
    `/**`,
    ` * Functional route guard for the ${routeName} route.`,
    ` * Redirects unauthenticated users to /login.`,
    ` */`,
    `export const ${camel}Guard: CanActivateFn = () => {`,
    `  const auth = inject(AuthService);`,
    `  const router = inject(Router);`,
    '',
    `  if (auth.isAuthenticated()) {`,
    `    return true;`,
    `  }`,
    '',
    `  return router.createUrlTree(['/login'], {`,
    `    queryParams: { returnUrl: '/${routeName}' },`,
    `  });`,
    `};`,
    '',
  ].join('\n');

  files.push({ path: path.join(targetDir, `${routeName}-auth.guard.ts`), content });
}

// ─── Resolver ────────────────────────────────────────────────
function buildResolverFile() {
  const content = [
    `// ${routeName}-detail.resolver.ts — generated by scaffold-route`,
    `import { inject } from '@angular/core';`,
    `import { ResolveFn, ActivatedRouteSnapshot } from '@angular/router';`,
    `import { ${className}Service } from '@core/services/${routeName}.service';`,
    `import { LoggingService } from '@core/services/logging.service';`,
    `import { catchError, of } from 'rxjs';`,
    '',
    `/**`,
    ` * Resolves ${routeName} detail data before the route activates.`,
    ` * Returns null on failure so the component can display an error state.`,
    ` */`,
    `export const ${camel}DetailResolver: ResolveFn<any> = (route: ActivatedRouteSnapshot) => {`,
    `  const service = inject(${className}Service);`,
    `  const logger = inject(LoggingService);`,
    `  const id = route.paramMap.get('id') ?? '';`,
    '',
    `  logger.info('${className}DetailResolver', \`Resolving detail for id=\${id}\`);`,
    '',
    `  return service.getById(id).pipe(`,
    `    catchError((err) => {`,
    `      logger.error('${className}DetailResolver', \`Failed to resolve: \${err.message}\`);`,
    `      return of(null);`,
    `    }),`,
    `  );`,
    `};`,
    '',
  ].join('\n');

  files.push({ path: path.join(targetDir, `${routeName}-detail.resolver.ts`), content });
}

// ─── Main ────────────────────────────────────────────────────
buildRoutesFile();
if (includeGuards) buildGuardFile();
if (includeResolver) buildResolverFile();

log(`Generated ${files.length} file(s)`);
process.stdout.write(JSON.stringify({ files }, null, 2) + '\n');
