#!/usr/bin/env node
/**
 * check-stack.js — Checksum-based stack detection hook
 *
 * Detects Angular version and installed packages from project files.
 * Writes .orch/cache/stack.yaml and .orch/cache/stack.checksum.
 *
 * Cascading fallback: cache (checksum match) → detect → pin → default
 * Exit 0 always — never blocks the orchestrator.
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const PROJECT_ROOT = process.env.PROJECT_ROOT || process.cwd();
const ORCH_DIR = path.join(PROJECT_ROOT, '.orch');
const CACHE_DIR = path.join(ORCH_DIR, 'cache');
const STACK_PATH = path.join(CACHE_DIR, 'stack.yaml');
const CHECKSUM_PATH = path.join(CACHE_DIR, 'stack.checksum');
const LOG_PATH = path.join(CACHE_DIR, 'resolution-log.json');
const CONFIG_PATH = path.join(ORCH_DIR, 'config.yaml');
const DEFAULT_VERSION = '19';
const MAX_LOG_ENTRIES = 50;

// --- Utility: read file or return null ---
function safeRead(filePath) {
  try { return fs.readFileSync(filePath, 'utf8'); } catch { return null; }
}

// --- Compute SHA-256 checksum of key project files ---
function computeChecksum() {
  const files = ['package.json', 'angular.json', 'nx.json', 'tsconfig.json'];
  const hash = crypto.createHash('sha256');
  for (const file of files) {
    const content = safeRead(path.join(PROJECT_ROOT, file));
    if (content) hash.update(file + ':' + content);
  }
  return hash.digest('hex');
}

// --- Detect stack from package.json ---
function detectStack() {
  const raw = safeRead(path.join(PROJECT_ROOT, 'package.json'));
  if (!raw) return null;

  try {
    const pkg = JSON.parse(raw);
    const deps = { ...pkg.dependencies, ...pkg.devDependencies };

    // Detect Angular version
    const angularCore = deps['@angular/core'];
    let angularVersion = null;
    if (angularCore) {
      const match = angularCore.replace(/[\^~>=<\s]/g, '').match(/^(\d+)/);
      if (match) angularVersion = match[1];
    }

    // Detect Nx
    const nxCore = deps['@nx/angular'] || deps['@nrwl/angular'] || deps['nx'];
    let nxDetected = !!nxCore;

    // Detect key packages
    const packages = [];
    const interesting = [
      '@ngrx/store', '@ngrx/signals', '@angular/material',
      'primeng', 'ag-grid-angular', 'plotly.js', '@nx/angular',
      'jest', 'karma', 'cypress', '@playwright/test'
    ];
    for (const p of interesting) {
      if (deps[p]) packages.push({ name: p, version: deps[p] });
    }

    // Check for angular.json or nx.json
    const hasAngularJson = fs.existsSync(path.join(PROJECT_ROOT, 'angular.json'));
    const hasNxJson = fs.existsSync(path.join(PROJECT_ROOT, 'nx.json'));

    return {
      framework: 'angular',
      angular_version: angularVersion,
      nx: nxDetected || hasNxJson,
      monorepo: hasNxJson,
      build_tool: hasAngularJson ? 'angular-cli' : (hasNxJson ? 'nx' : 'unknown'),
      packages,
      detected_at: new Date().toISOString()
    };
  } catch {
    return null;
  }
}

// --- Read manual version pin from .orch/config.yaml ---
function readConfigPin() {
  const raw = safeRead(CONFIG_PATH);
  if (!raw) return null;
  // Simple YAML parse for angular_version: "XX"
  const match = raw.match(/angular_version:\s*["']?(\d+)["']?/);
  return match ? match[1] : null;
}

// --- Cache read (returns stack object if checksum matches) ---
function tryReadCache(currentChecksum) {
  try {
    const cachedChecksum = safeRead(CHECKSUM_PATH);
    if (!cachedChecksum || cachedChecksum.trim() !== currentChecksum) return null;
    const cachedStack = safeRead(STACK_PATH);
    if (!cachedStack) return null;
    return { stack: cachedStack, source: 'cache' };
  } catch {
    return null;
  }
}

// --- Cache write (silent failure) ---
function tryCacheWrite(stackYaml, checksum) {
  try {
    fs.mkdirSync(CACHE_DIR, { recursive: true });
    fs.writeFileSync(STACK_PATH, stackYaml, 'utf8');
    fs.writeFileSync(CHECKSUM_PATH, checksum, 'utf8');
  } catch {
    // Silent failure — cache is optional
  }
}

// --- Append to resolution-log.json (max 50 entries, rotate oldest) ---
function appendLog(entry) {
  try {
    let log = [];
    const raw = safeRead(LOG_PATH);
    if (raw) {
      try { log = JSON.parse(raw); } catch { log = []; }
    }
    log.push({ ...entry, timestamp: new Date().toISOString() });
    if (log.length > MAX_LOG_ENTRIES) {
      log = log.slice(log.length - MAX_LOG_ENTRIES);
    }
    fs.mkdirSync(CACHE_DIR, { recursive: true });
    fs.writeFileSync(LOG_PATH, JSON.stringify(log, null, 2), 'utf8');
  } catch {
    // Silent failure
  }
}

// --- Convert stack object to YAML string ---
function stackToYaml(stack) {
  let yaml = '# Auto-generated by check-stack.js — do not edit\n';
  yaml += `framework: ${stack.framework}\n`;
  yaml += `angular_version: "${stack.angular_version}"\n`;
  yaml += `nx: ${stack.nx}\n`;
  yaml += `monorepo: ${stack.monorepo}\n`;
  yaml += `build_tool: ${stack.build_tool}\n`;
  yaml += `detected_at: "${stack.detected_at}"\n`;
  if (stack.packages && stack.packages.length > 0) {
    yaml += 'packages:\n';
    for (const p of stack.packages) {
      yaml += `  - name: "${p.name}"\n    version: "${p.version}"\n`;
    }
  }
  return yaml;
}

// --- Main ---
function main() {
  const checksum = computeChecksum();
  let source = 'default';

  // 1. Try cache
  const cached = tryReadCache(checksum);
  if (cached) {
    appendLog({ source: 'cache', checksum });
    process.exit(0);
  }

  // 2. Try detection
  let stack = detectStack();
  if (stack && stack.angular_version) {
    source = 'detected';
  } else {
    // 3. Try config pin
    const pinned = readConfigPin();
    if (pinned) {
      stack = stack || { framework: 'angular', packages: [], detected_at: new Date().toISOString() };
      stack.angular_version = pinned;
      stack.nx = stack.nx || false;
      stack.monorepo = stack.monorepo || false;
      stack.build_tool = stack.build_tool || 'unknown';
      source = 'pinned';
    } else {
      // 4. Default fallback
      stack = stack || { framework: 'angular', packages: [], detected_at: new Date().toISOString() };
      stack.angular_version = DEFAULT_VERSION;
      stack.nx = stack.nx || false;
      stack.monorepo = stack.monorepo || false;
      stack.build_tool = stack.build_tool || 'unknown';
      source = 'default';
    }
  }

  const stackYaml = stackToYaml(stack);
  tryCacheWrite(stackYaml, checksum);
  appendLog({ source, checksum, angular_version: stack.angular_version });
}

try {
  main();
} catch {
  // Exit 0 always — never block the orchestrator
}
process.exit(0);
